name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: <your-project-id>
  DOCKER_REGISTRY: gcr.io

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '313.0.0'
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY
- name: Build and Push Docker Image
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker build -t $DOCKER_REGISTRY/$GCP_PROJECT_ID/service1:$GITHUB_SHA -f ./service1/Dockerfile .
          docker push $DOCKER_REGISTRY/$GCP_PROJECT_ID/service1:$GITHUB_SHA

      - name: Deploy to Kubernetes
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
        run: |
          helm upgrade --install service1 ./service1-helm --set image
yme-vtoh-zuf
